### ISSUE TITLE
Doesn't work with New Google Calendar

### ISSUE THREAD

**Issue by czekaj** [alter-ego/google-calendar-scroll-disabler#9]
Google has just released the new Google Calendar web app and the scroll disabler doesn't work anymore.

More info: https://www.blog.google/products/g-suite/time-refresh-introducing-new-look-and-features-google-calendar-web/

**Comment by chrisrosa** [comment]
same. macOS 10.13 + Chrome 62.0.3202.62.

**Comment by czekaj** [comment]
I'd love to hear @hamen's take on it. I noticed that Google did something ugly with the New Calendar. They switched to a Google Inbox-like UI framework which generates HTML elements randomly and it's much much harder to find what you're looking for. Therefore it may be challenging to write a working Scroll Disabler for it.

**Comment by hamen** [comment]
Hi all and thank you for the report. That's unfortunate, but I'm gonna still trying to work this out next weekend 💪🏻

**Comment by hamen** [comment]
Any chance you can give this version a try, please?
[google-calendar-scroll-disabler.zip](https://github.com/alter-ego/google-calendar-scroll-disabler/files/1404192/google-calendar-scroll-disabler.zip)

1. Remove the previous version.
2. Unpack the `.zip` file
3. Chrome -> Extensions -> Load unpacked extension
4. Reload Google Calendar

Thank you very much 😄

**Comment by czekaj** [comment]
Thanks for working on it, Ivan! 

It works only partially.
So at first, after reloading, it doesn't work and I can still scroll but as soon as I click any day to add an event it starts working.

**Comment by hamen** [comment]
There is a 5 seconds timer, because I'm waiting for the asynchronous stuff to load.
Can you do a test for me please? Load the page and wait 6 seconds and then try to scroll.
If it works, we can think about reducing the timer, looking for the sweet spot.
Thanks

**Comment by apphancer** [comment]
Thanks Ivan. It's working fairly well. 
Just one small issue that I have noticed so far is that the scroll is re-enabled after a new event screen is triggered (regardless if the event gets created or the the Esc key is pressed without creating an event).

**Comment by chrisrosa** [comment]
This is working fine for me. I can definitely work with a timer. Thanks

**Comment by MoFugga** [comment]
Hello, 

New here.  I installed your extension, and when it loads, after the small delay, I lose the ability to scroll all together. What can I provide you to help?

Kevin

**Comment by algoroq** [comment]
Hello, thanks for this extension. 

I tried version 0.3:

- after 5 seconds scroll ability is completely disabled 
- when I click the "next month" button, the scroll will resume as well as without extension

**Comment by heyfletch** [comment]
version 0.3 is working well for me. I'll report back if I find any issues. I'm a light-user.

**Comment by DavGoodvibes** [comment]
It work for me BUT the problem is back as soon you save a new event.

**Comment by heyfletch** [comment]
Same. Works, until saving a new event.

**Comment by apphancer** [comment]
I have a made a few changes to the code and made a Pull request
Can you take a look at Pull request #10

**Comment by hamen** [comment]
Thank you for the PR, Martin. I'm gonna look at it ASAP.

**Comment by brendanfalkowski** [comment]
Appreciate the work on this, will be hammering Google Calendar's feedback form that they still haven't included a setting to disable scrolljacking.

**Comment by x1c0** [comment]
Hi @hamen thank you for this great extension! any plans when 0.3 version will be released for the web store?

**Comment by hamen** [comment]
Hi all and sorry for the delay. I'm gonna be on this next weekend, polish everything and release a new version.
Thank you all for the support and your patience <3

**Comment by danielosborn** [comment]
@hamen Thank you for your work on this! Greatly helpful!

**Comment by hamen** [comment]
I eventually managed to merge @apphancer https://github.com/alter-ego/google-calendar-scroll-disabler/pull/10 PR : it looks great!

I have just published version `0.4` (still rolling out tho). I gave it a quick test drive. Please, let me know if you see something wrong.

Once again, thank you @apphancer ❤️

**Comment by apphancer** [comment]
I am glad my contribution could help. Thanks @hamen for starting this extension in the 1st place

**Comment by UpstairsEmpire** [comment]
@hamen Thanks for the continued work on this extension. 

I haven't switched over to the new Google Calendar web app design yet, and with this new update, I lost functionality in the _old_ web app design! (Google allows you to choose which app to use at the moment.)

I tested in the new Google Calendar app and it works successfully. 

Possible to restore functionality in the old web app, for those of us who prefer it? 

Chrome in MacOS 10.13.12

**Comment by brendanfalkowski** [comment]
Thank you! Working well from my testing.

Hint: try restarting Chrome to get the update. The extension management screen doesn't have a way to manually update apparently.

**Comment by UpstairsEmpire** [comment]
@hamen The issue is still occurring. I've restarted chrome, reinstalled the extension, restarted my computer and restarted chrome again! I've also confirmed I have been running v0.4

**Comment by heyfletch** [comment]
v 0.4 does not solve clickjacking for me. Chrome 69. MacOS Mojave.

**Comment by x1c0** [comment]
Please try this PR -> https://github.com/alter-ego/google-calendar-scroll-disabler/pull/15

works for me on Chrome 69 - MacOS Mojave.

**Comment by heyfletch** [comment]
@x1c0 Thanks! #15 works for me.

**Comment by hamen** [comment]
A new release is rolling out. Please, give it a try.

**Comment by knumat** [comment]
@hamen Thanks for doing the 0.5 release!  It seems to be working for me.

**Comment by UpstairsEmpire** [comment]
@hamen 0.5 release is working perfect for me on MacOS Mojave (10.14) running Chrome 69.0.3497.100 (Official Build) (64-bit).

Now if only we had a Safari version! Pushing my luck? :)

**Comment by hamen** [comment]
🤔 I have no idea. Does Safari have extensions? I'm not using Safari, so I know very little about it.

**Comment by UpstairsEmpire** [comment]
@hamen Yes it does have extensions! Through chrome unfortunately has many, many more. I have my fingers crossed on this one. Why doesn't Google just fix this bug?!
